name: github pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  slidedeck:

    runs-on: ubuntu-latest

    container: 
      image: fedora:32
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "True"
        NPM_CONFIG_PREFIX: ~/.npm-global

    strategy:
      matrix:
        # Include all major maintenance + active LTS Node.js versions.
        # https://github.com/nodejs/Release#release-schedule
        node: [14]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: reset node config
        run: |
          npm config list
          npm config set prefix '~/.npm-global'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '2'

      - name: Check pandoc version
        run: |
          dnf install -y make wget sed curl jq pandoc
          pandoc --version
          npm config list

      - name: Prepare the environment
        run: |
          sudo make prepare

      - name: build slides
        run: |
          make index.html

      # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-static-site-generators-with-python
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
